name: Docker Image CI
on: [push]

jobs:
    build:
      runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v1
          - name: Build the docker-compose
            run: |
              docker-compose build
              docker-compose up -d
          - name: Check running containers
            run: docker ps -a
          - name: Check logs
            run: docker logs backend
